### ISSUE TITLE
There is no .env.template file for gateway

### ISSUE THREAD

**Issue by orlovmyk** [DefGuard/docs#13]
https://github.com/DefGuard/docs/blob/fc77a89cf677f97369c4e57b18e97a50468d8e49/features/setting-up-your-instance/gateway.md?plain=1#L64

Tried to do these steps, but they didn't work for me as far as `.env.template` does not exist in https://github.com/DefGuard/gateway.git

I guess better to either remove this line, either add `.env.template`

**Comment by wojcik91** [comment]
Updated the compose file in https://github.com/DefGuard/deployment/pull/23 and fixed the incorrect link in deployment docs.
