### ISSUE TITLE
Add desktop client docs

### ISSUE THREAD

**Issue by wojcik91** [DefGuard/docs#16]
Document desktop client architecture & activation process/usage. 
Important: remember to mention proxy & core version requirements.

**Comment by teon** [comment]
Should be a separate "section" **Desktop Clients** with the following chapters:
- Enrollment
- Remote desktop activation (with screenshots - walkthrough)
- Architecture & Deployment
- For developers

**Comment by teon** [comment]
Add info to homepage of docs (in architecture) about proxy/enrollment (as a requirement for Desktop Client)

**Comment by teon** [comment]
And all docs of configuring VPN client (Configuring a device for a new VPN Location) add info about desktop client and write that this is configuration for official (or other) Wireguard Clients
