### ISSUE TITLE
User help MFA in docs

### ISSUE THREAD

**Issue by teon** [DefGuard/docs#22]
1. Describe that DG supports MFA when:
- VPN has enabled MFA (screenshot)
- describe how MFA is working:
- flow diagram:
  - user -> proxy <- core ...
  - MFA OK -> proxy <- core -> GW WG PSK KEY
- WARINING: If MFA flag will be changed on a selected VPN Location, all clients must do Instance Update, for now we only support instance update (link to instance update)
2. information that MFA is only available for TOTP & EMAIL + link that email requires SMTP config (link do docs)
4. inform that if a user has not enabled MFA the following error will occur (screenshot)
5. example happy path when connected

**Comment by blazej-teonite** [comment]
https://app.gitbook.com/o/Z3mGSAbEj9iLdZ7cNFlL/s/hM5HQk0xXl585Dm4YMUV/features/desktop-client/multi-factor-authentication

**Comment by blazej-teonite** [comment]
@wojcik91 Please add the flow diagram.
