### ISSUE TITLE
Add to documentation Standalone / Package based installation

### ISSUE THREAD

**Issue by cpprian** [DefGuard/docs#29]

**Comment by cpprian** [comment]
Describe in the documentation how to run and configure packages: core, gateway and proxy.
- [x] Examples should be from Debian 12.
- [x] Describe quickly what are these three packages and why in this direction are enabled.
- [x] Separate walkthrough by core/gateway and proxy

**Comment by teon** [comment]
https://defguard.gitbook.io/defguard/admin-and-features/setting-up-your-instance/standalone-package-based-installation
