### ISSUE TITLE
Mikrotik Gateway Error

### ISSUE THREAD

**Issue by PedroBuffon** [DefGuard/docs#39]
Hi, i'm trying to setup the mikrotik gateway but i'm encountering some errors
`[2024-11-21T13:21:21Z ERROR defguard_gateway::gateway] Couldn't retrieve gateway configuration from the core. Using gRPC URL: defguard.buffon.cloud. Retrying in 10s. Error: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }`

**Comment by teon** [comment]
@PedroBuffon with just the setting of gRPC url to the domain the gateway assumes the url is http://defguard.buffon.cloud  - meaning the gRPC on core is on port 80 - and that's probably not possible. Please correct the url.
If you have more errors please set the logs to debug (more in docs: https://docs.defguard.net/admin-and-features/setting-up-your-instance/configuration#environmental-variables-arguments) and re-open the issue with more logs.
